### ISSUE TITLE
Hardware not responding to synapse

### ISSUE THREAD

**Issue by OAlienado** [AndrewBabbitt97/AuraConnect#25]
Hello! First of all, your work is amazing and thank you so much for it!

So, I got AuraConnect up and running, Synapse shows aura and Armoury Crate get of that mode that shows it being controlled by SDK. 

All fine, but... the colors just stuck as they were when synapse opened and, that's it. I can change as much as I want in Synapse, but the Motherboard and ARGB strip just won't respond. Oddly enough, razer hardware works flawlessly (I tryed with a Goliathus Chroma).

Tryed on my ROG Strix x470-f and Prime B450m, but the situation was the same with both.

One thing that called by attention is that I have a Wraith Prism cooler running with a native CoolerMaster Chroma compatible software. And, for my surprise, the Prism behaviored just as aura did (shows up in Synapse, but got stuck in one color and don't respond to any config I put on Synapse). I only tested this on the Prime b450, since changing coolers is kinda messy...

Is there a solution for this? Thanks in advance!

P.S.: I also tryed the iCue connect... But this one is even weirder, since it says that there is a SDK running, but won't even show up in Synapse... But that is a point for another time hehehe

**Comment by djchristoph** [comment]
Hi OAlienado, I had the same problem and I found that if I open the task manager, go to services, find the Aura Connect service, stop it then restart it, and do the same for the Lighting service, everything starts working fine again. I keep checking back here hoping that maybe Andrew will introduce some sort of refresh command that does this instead of having to do it manually. Hope this works for you!

Great work Andrew! Looking forward to the next release!

**Comment by OAlienado** [comment]
Thanks, mate! I reinstalled Synapse 3 and AuraConnect on both my PCs to try out your solution, and here's what I've got:

On my b450m: Just for a relief of conscience, I erased the old AuraConnect folder before installing and logged in with my razer account. And now, all of sudden, thing started working like a charm! And it's awesome!

On my x470-f: Blue screen of death. 

Seriously, I installed AuraConnect, resintalled and boom, BSOD. Reboot, BSOD. So I made a full reinstall, with just essencial drivers, Aura, Synapse and AuraConnect. Guess what? BSOD. AGAIN.

As I type, my pc is running updates after being formated a second time... And I am afraid of trying anything and end up needing to format it again. I am not even installing Aura, since I don't know for sure if I must install it or Armory Crate (or ROG Gaming Center. Btw, does anyone know the difference between Armoury Crate and ROG Gaming Center?)

In any case, thank you for you advice, which led me to finally get it to work on my B450. As for my x470, since the BSOD happened even with a fresh windows, I believe it must be some hardware incompability - but I guess only Andrew can say for sure.

**Comment by AndrewBabbitt97** [comment]
I would need a BSOD dump file to tell what's going on.

I could only assume it's something with AURA/Synapse as BSODs tend to be caused by driver issues (AuraConnect doesn't install a driver at all, also doesn't really have the ability to cause a BSOD.) We consume the Aura SDK and the Synapse Connect SDK, it would be happening in one of those those 3rd party components.

**Comment by OAlienado** [comment]
> I would need a BSOD dump file to tell what's going on.
> 
> I could only assume it's something with AURA/Synapse as BSODs tend to be caused by driver issues (AuraConnect doesn't install a driver at all, also doesn't really have the ability to cause a BSOD.) We consume the Aura SDK and the Synapse Connect SDK, it would be happening in one of those those 3rd party components.

First of all, thanks for you reply and for the software! As for the dump file, I guess it was lost during the format...

All I know is that the code was "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED" and what failed was the "stornvme.sys", but when I ran a "sfc /scannow", it found no errors. Also, I did some digging and found someone with the same BSOD caused by RGB Fusion, and since mine happened right after I installed two RGB related softwares, I figured it was being caused or by Synapse, or by AuraConnect.

Anyway, I'll try again. Just one thing, is it better to use Armoury Crate, ROG Gaming Center or good ol' Aura?

Thanks again @AndrewBabbitt97!

**Comment by AndrewBabbitt97** [comment]
stornvme.sys is Microsofts built in NVME driver. So its very odd that it would come from that.

I would need a bsod dump file to tell fully what happened.

As for what software you should use, its up to you. They all install the same lighting service, so it doesn't matter.

**Comment by OAlienado** [comment]
So, yesterday I took the day to dive into this situation. And, after more than 4gb of bsod dump files, 5 fresh installations of windows and bugging my backplate in such a way that it now only shows the last static color when aura is off, I finally made it to work.

About the bsod, I got one every single time I tryed to restart  lighting service. They started to show up after I installed icue and synapse.

Anyway, in short, I:

1 - Made a fresh install of windows, only with chipset, video and audio drivers, plus lastest windows update to version 1903, rebooting after each installation;

2 - installed armoury crate, reboot;

3 - installed icue, reboot;

4 - installed synapse; reboot;

5 - installed aura connect, reboot;

6 - profit! No more bsod or anything.


A few things to point out:

For some reason, my backplate sometimes respond do Aura Connect + Synapse, sometimes not. And, as I said before, it now stucks with the last static color I put on crate (no more beautifull rainbow colors while booting =/). Curious part is, my addressable rgb header still shows rainbow pattern, just the backplate goes different.

I uninstalled crate, installed the icue plugin, reinstalled crate and managed to control my vengeance pro RGB memories with crate. But, when Aura Connect + Synapse is on, the memories get stuck in a single color and do not follow along with the rest of the system, so I uninstalled the plugin.

For some reason, my Armoury Crate can no longer show the options for my motherboard. It blinks the options, than the screen goes blank in a dark gray color.

If you guys want my dump files, just let me know. Only thing is that I am not sure how to handle such big files, I could not even read then ^^'' (noob, I know...)

In any case, it's now working and I am pretty happy. Thank you again, @AndrewBabbitt97 , for the aid, and @djchristoph for the insight about the services!

Best regards,

Vinicius.

P.S.: now waiting for the Corsair Connect hehehe... that one does not even show up in synapse, and I am afraid of trying it out and screwing what I already got...

**Comment by AndrewBabbitt97** [comment]
I have another piece of software for iCUE, however I am trying to resolve issues here first before I move onto fixing that. Stay with what you have for the time being.

ASUS MBs can store a static color, its something internally in the MB. Its been a while since I have messed with that, I know theres some options in bios for it.

Dont worry about the bsod files, if it comes back somehow let me know and we will go from there. If it happens please feel free to reopen this issue.

**Comment by djchristoph** [comment]
I find the more competing RGB software I install, the bigger knot it ties within all of it. I don't have any Corsair stuff, just Asus and Razer, and my fans are Thermaltake but I've eliminated the TT software because it clashes with Aura. I've experienced most of what you're describing other than the BSOD. I haven't had anything crash like that. The cleanest I've had everything running is right after a fresh install of Windows with minimal programs competing for control. My lights were doing strange things from time to time and I discovered that there were profiles for specific games within each of the RGB softwares that were trying to run simultaneously and locking things up. I turned off the in game effects in Armoury Crate and deleted any game profiles in Synapse and it helped. 
         As Andrew said in an earlier post, you may be having some driver conflicts. I use a program called Driver Easy. You may be familiar with it, but if not, it's a program that scans your computer and compares your drivers with a database. It then downloads and installs all the current drivers. I find it particularly handy when starting with a fresh install of Windows.
