### ISSUE TITLE
Error 1053: The service did not respond in a timely fashion

### ISSUE THREAD

**Issue by SirBrent99** [AndrewBabbitt97/AuraConnect#33]
I've installed AuraConnect but the service is not able to start.  If I try to run the AuraConnect.exe file by itself I get another error.  Have you seen this before?

![Annotation 2020-04-11 090458](https://user-images.githubusercontent.com/63505217/79046078-33c43000-7bd4-11ea-9ddd-4b0cc6c0298f.png)

![Annotation 2020-04-11 090558](https://user-images.githubusercontent.com/63505217/79046081-37f04d80-7bd4-11ea-913a-c436e2ef9c4b.png)

**Comment by duduw1** [comment]
Hello I have the same error.
synapse 3.5.331.33010
Lighting_Control_1.07.79.zip

**Comment by AndrewBabbitt97** [comment]
This is an issue with your AURA install. The AURA COM components aren't properly registered on your PC and thus AuraConnect can't connect to Aura.

**Comment by duduw1** [comment]
I did a new installation, and now it presents this error, not to take a print. 
![eero2](https://user-images.githubusercontent.com/20798083/79061309-5a7e7700-7c65-11ea-9ecb-0d5dc32ba63b.png)

**Comment by AndrewBabbitt97** [comment]
You didn't get the actual error, only the part of the stack Trace. You would have to scroll up to see the error.

**Comment by duduw1** [comment]
hello incredible, I got it, thanks to you. Thank you very much

**Comment by AndrewBabbitt97** [comment]
Good to hear you got it working.

**Comment by ultrajounin** [comment]
I am getting this error randomly, I recently had to reinstall armoury crate, razer synapse 3 and aura connect. Worked fine for a few days then stops. When I try to start AuraConnect service the error pops up. But by the way thank you for creating this because it has worked perfectly for the last few months. Im not a power user but suspect either a windows or Razer update caused this issue because the problem started after a few updates.
