### ISSUE TITLE
connecter mais...

### ISSUE THREAD

**Issue by Geoffrey-lusitano** [AndrewBabbitt97/AuraConnect#35]
connecter mais modification non prise en compte, reste fixe.

X470 asus gaming f

merci d'avance

**Comment by AndrewBabbitt97** [comment]
Please bear in mind I only speak English, and my ability to support you without it will be limited.

If you are having issues I need logs from C:\ProgramData\AuraConnect\Logs

**Comment by Geoffrey-lusitano** [comment]
okay sorry, i can speak anglais but bad ^^. okay i try this, this weekend. thanks guy

**Comment by OAlienado** [comment]
@Geoffrey-lusitano Vc é português? Seu texto parece mais francês, mas me chamou atenção o "lusitano" no nick... se for, pode perguntar aqui em português que eu traduzo pra ele.

I just asked if OP is from Portugal (because of his nickname... "lusitano" means "native from Portugal"), because, since I'm from Brazil, we speak the same language. So I offered him to post his issues in Portuguese and let me do the translation.

**Comment by AndrewBabbitt97** [comment]
@Geoffrey-lusitano You still around?

**Comment by AndrewBabbitt97** [comment]
Issue has gone stale, going to close. If more assistance is needed feel free to reopen.
