### ISSUE TITLE
Setup Docs?

### ISSUE THREAD

**Issue by jameswlane** [AndrewBabbitt97/AuraConnect#37]
I found this on the Razer Forums, I have installed it. But I can't find a way to setup the sync between Aura. I went into the folder it installed into, and ran the AuraConnect application. It opened the command line and ran some items and closed it. I can't find anything in Aura or Synapse to get it to work.

Is there something special I need to do to get it to work?

Thank you for developing this and maintaining it.

**Comment by AndrewBabbitt97** [comment]
There is nothing special you need to do to get it to work, if it doesn't work out of the box restart your PC. It runs as a background service on your PC.

If you still cant get it to work i would need logs from C:\ProgramData\AuraConnect\logs directory.

**Comment by AAlchemy** [comment]
I found I had to completely uninstall and reinstall all the ASUS Aura software (without opening or using any of it), then install AuraConnect and only adjusting Aura from the Razor Chroma Studio (Never in the ASUS app). This maybe just me, and might not have contributed to a working setup, but I could not get sync before doing this.

**Comment by AndrewBabbitt97** [comment]
Yes, you cant use the ASUS software to control device lighting with this software. Its all done through Razer Synapse. I have added a FAQ section to the readme to add a few points to note for people.

I have seen installs of AURA that fail to register their COM components in windows Correctly, this has been known to cause issues. Can always be fixed with a AURA reinstall.
