### ISSUE TITLE
Unable to hook Synapse to Aura

### ISSUE THREAD

**Issue by lordcraptor** [AndrewBabbitt97/AuraConnect#42]
Hi,

I'm using Asus x570 E Gaming Board. Synapse installed accordingly and running well together with Thermaltake TT RGB Plus apps.

However, I'm unable to hook synapse with Aura. I can see Aura icon in Synapse but the light was not changing as per Synapse setting.

Please advice. Let me know if you need more info from me.

**Comment by Raidentaylor** [comment]
Hi.

You use kaspersky? I had and only work if i disable "System Watcher", i think that's what it's called.

**Comment by AndrewBabbitt97** [comment]
Antivirus is a leading cause of issues, so confirm this please and report back.

**Comment by KyleStilkey** [comment]
I'm also having the same issue as well, it just refuses to take any of the changes done on Synapse. It just stopped working randomly and now refuses to communicate with it.

I'm just running Windows Defender, so not sure if there is any suggestions I could try.

**Comment by KyleStilkey** [comment]
Just wanted to leave an update on my situation.

It seems that Microsoft may have pushed out a security update that interferes with ASUS Aura installing correctly. I was lucky that a old restore did work as I was having issues before with it working.

Once I restored back to a older date I was able to run AURA Sync without any issues again as the missing/blocked files during install were intact this time. I was still having issues with AuraConnect communicating with the system.

As soon as I ran AURA in the background it's like it kicked AuraConnect into gear and it allowed it to take over and communicate with Synapse once again.

I believe that this may be more of an ASUS issue again and they will need to work out the bugs to resolve the problems. I had a old system that is on 1909 that's not been updated in months and I had no problems with any of this working but I have my system on build 2004 (May Update) and another on 1909 fully up to date and they too have the install issues with AURA.

I hope ASUS moves more devices over to their Armoury software as that works wonders but the device support is very low.

Anyways, just wanted to at least leave an update on the matter.

**Comment by AndrewBabbitt97** [comment]
You don't need full Aura in the first place, only Lighting Service which is installed by both Aura and ArmoryCrate (you can find the service installer in a subfolder in the Aura download).

I currently use ArmoryCrate as it's how I get all my Driver's from ASUS and the only way I can get the display on my Maximus XI Formula to change, the independent utility for it stopped working for me after a while and I didn't realize they moved the functionality to Armory Crate till a while ago. Been using it since.

On note of updates, I use 2004 and it's where all my dev work is done. I currently use the latest insider slow ring build with all updates applied and everything is working well.

Of note.... I will eventually need to drop support for non Armory Crate installs, just due to how ASUS is handling things. Not entirely certain of this, but it may wind up being what happens.

**Comment by KyleStilkey** [comment]
This issue is Aura services are being blocked during installation, if you previously have it installed its not an issue. This is a known issue you can find all over their forums, this same problem a cured when 1909 released and prevented installs due to security reasons.

Having the lighting services is also not enough as it if loses the ability to communicate with your devices, the only fix currently is running Aura or Armoury and changing your lighting effects and then restarting Synapse and it will start to communicate again. Do not know why but this has been a fix that resolves it anytime it stops working. 

Removing Aura and switching to Armoury should only happen once they have full support of devices. Currently the list is very small and will just remove the ability for people to use this.

There current plan right now is to update and release a new Forum and structure for better communication and feedback and then look at supporting more devices but with the things going on in the world they are a bit delayed for the time being.

**Comment by AndrewBabbitt97** [comment]
My install is clean, as in literally installed latest insider build from ISO a week ago, then updated, and then ArmoryCrate install. That's why I'm confused on this issue as it shouldn't be working if that's the case.

Now I'm not going to deny that this may be an issue, however I'm not able to replicate it at all.

With this said, I have been getting a larger influx of potentially Aura related issues in the past weeks. I may start putting issues on hold and associating them to this issue if that's the case.

If you could do a huge favor and monitor the situation on the AURA side and keep this issue updated with relevant info, that would be fantastic.

**Comment by KyleStilkey** [comment]
Yeah, it's with the Aura side, whatever they are doing is being blocked but Armoury is working perfectly fine, but sadly users can't use Armoury until they support their hardware.

Im currently on a Crosshair Hero VI x370 and its not supported but the Hero VII got added around Nov last year but I'm not going to drop money for support.

If users can use it, for sure use it as it's miles better but sadly there is a lot of users stuck at the moment and plus ASUS doesn't do a great job and letting users know this unless you are looking for it or randomly hear about it. 

I may have some hardware here that has Armoury support and will mess around with it if I can so I can help provide more data on both fronts, but as it stands now, if communication just stops working, the only way to jump start it is by running Aura and letting it take control and restarting Synapse to start again. I've got a handful of hardware setups that this happens with and seems to be the only way to jump start it, no amount of service restarts, reboots or installs work, it's almost like the lighting service itself has just lost all ability to communicate with the motherboard or hardware. 

If I don't have any supported hardware then maybe I'll look at getting a cheap board that supports it and seeing if there is some sort of difference with it if communication stops working between the services.

**Comment by KyleStilkey** [comment]
Update my wife's B450 board has support with Armoury, I'll get her moved on over and get everything setup through it and see if I can trigger the same issues to happen or not. Funny how a sub $100 board has support over a $300 one.

I'll also keep an eye out for any Aura side updates and so forth and see if we can at least track down as much issues as possible to make it easier for others to find possible fixes and so forth.

**Comment by lordcraptor** [comment]
I gave up trying to solve the issue. Then I decided to reformate the windows and performed a clean installation. It works immediately!!!!!!!

No issue observed even after updating to the latest windows. I think I mess up with the aura installation previously.

Nevertheless, cool apss by Andrew! Thank you.

**Comment by KyleStilkey** [comment]
> I gave up trying to solve the issue. Then I decided to reformate the windows and performed a clean installation. It works immediately!!!!!!!
> 
> No issue observed even after updating to the latest windows. I think I mess up with the aura installation previously.
> 
> Nevertheless, cool apss by Andrew! Thank you.

What version of Windows 10 are you on? Trying to see if we can track down some more information. Are you using Aura or Armoury for your installation?

**Comment by lordcraptor** [comment]
> > I gave up trying to solve the issue. Then I decided to reformate the windows and performed a clean installation. It works immediately!!!!!!!
> > No issue observed even after updating to the latest windows. I think I mess up with the aura installation previously.
> > Nevertheless, cool apss by Andrew! Thank you.
> 
> What version of Windows 10 are you on? Trying to see if we can track down some more information. Are you using Aura or Armoury for your installation?

I'm on Microsoft Windows 10 Pro (Version 10.0.18363 Build 18363) and using Armoury for installation.

What I did was, fresh load Windows > Installed Armoury > Install this app > Install Kaspersky (to confirm above suspicion)

No issue observed up to date. all light sync perfectly. No delay and no lag even with Ambient Awareness setting.

**Comment by AndrewBabbitt97** [comment]
Just be aware Kaspersky is know to cause issues, and if any arise in the future I will require it to be entirely disabled/uninstalled.

I'm hoping to do quite a bit this weekend on improving things such as issue templates, docs, and some other things and Kaspersky being disabled/uninstalled will be a requirement for submitting issues it's just caused too many headaches in the past.

**Comment by KyleStilkey** [comment]
> > > I gave up trying to solve the issue. Then I decided to reformate the windows and performed a clean installation. It works immediately!!!!!!!
> > > No issue observed even after updating to the latest windows. I think I mess up with the aura installation previously.
> > > Nevertheless, cool apss by Andrew! Thank you.
> > 
> > 
> > What version of Windows 10 are you on? Trying to see if we can track down some more information. Are you using Aura or Armoury for your installation?
> 
> I'm on Microsoft Windows 10 Pro (Version 10.0.18363 Build 18363) and using Armoury for installation.
> 
> What I did was, fresh load Windows > Installed Armoury > Install this app > Install Kaspersky (to confirm above suspicion)
> 
> No issue observed up to date. all light sync perfectly. No delay and no lag even with Ambient Awareness setting.

Thanks for the update, so not on the latest 2004 update so it may be an issue with changes made with WIndows 10 and the Aura side and how it's being installed as Amoury has 0 issues. I'll keep picking away and getting more into it.

**Comment by KyleStilkey** [comment]
Just wanted to reach out and see if we can get some more info into this. The more I think about this I saw this once before and it was due to AMD's Chipset drivers preventing Aura from working and very well may be the same issue as I just tested on another users system who was on build 1903 and is getting this same issue but was working before I updated the chipset and then attempted a Aura update.

I sadly would need to do a test on a day off on a fresh install without the latest chipsets to see if this is the cause but wanted to see if others with the issue will respond back with more details about your system setups.

**Comment by AndrewBabbitt97** [comment]
And unfortunately I do not have an AMD system at this time (9900k + Maximus XI Formula). If you find anything let me know.

**Comment by KyleStilkey** [comment]
When I get some free time I will test this. I work weekends so I'll give it a test and setup a dual boot on and test this out and see if this is what's the problem. I will be sure to report back as soon as I can test this out.

**Comment by KyleStilkey** [comment]
Ok so I got caught up with work and acquired a new server, so I've been a bit busy but finally had some time. Just as I was about to run through some new updates, AMD pushed out a new Chipset driver and sure and behold the issues resolved. 

I'm 2 for 2 with the small testing I've done but it seems very well that AMD Chipset drivers may have been the cause of this. If anyone is getting this issue and is unable to run the Armoury software due to compatibility, then give these a try. I've create a troubleshooting steps below that I hope will help you and possibly other users do some fixes/reporting better as most issues stem from ASUS AURA.



###**BASIC TROUBLESHOOTING**

**INSTALL ASUS ARMOURY FIRST**
_ASUS ARMOURY seems to be much better in support. Even if your device doesn't show as supported on their website or your motherboard support page, try it anyways, they are terrible at updating these when support is added._
- Install ASUS ARMOURY. Restart when asked.
- Start the software up and let it update.
- Once updated you need to update the components inside the software itself too. Go to Settings > Update Center > Check for Updates. Restart once done.
- Check and see if your devices show up and are controllable and you can control your lighting effects. _*You should be able to select and control under the Devices tab, The AURA Sync tab may not be fully working for your device as this tab has many new features that it may not support. So long as you can make changes under the Devices Tab, this will use the ASUS Lighting Services Still._
- If it's not working or your device is not compatible, make sure to uninstall all services that ARMOURY has installed and go back to AURA.

**MY CPU USAGE IS TOO HIGH!**
This has nothing to do with ASUS CONNECT. ASUS CONNECT takes over the Asus Lighting Services and just allows for it to sync up with Razer Synapse. The high CPU usage seems to be related to the lighting effects selected. You can test this by opening up AURA or ARMOURY and changing the lighting effects to Static and the CPU usage being at nearly 0% but change it to another effect and you will see it's usage jump. This will mostly be seen by on lower to mid range CPU's and probably not noticed on higher end CPU's with high core counts due to the amount of workload they can do. Running Razer Synapse under a static color will still cause high CPU Usage as it's being seen as a "special effect." There is nothing you can do to fix this but to report the bug to ASUS and hope they fix the problem.

**SYNAPSE DOES NOT CONTROL MY ASUS DEVICES**
- Startup ASUS AURA. _*Make sure you see your devices showing, if your devices are missing like the motherboard, try the steps below._ 
- Select the option SELECT EFFECT. This should then open AURA for AURA CONNECT to take over and you should see your lights start working. 
- If still no luck, select one of the prebuilt in software's color effects. Apply the changes and then select the option SELECT EFFECT and it should take over. 

**DEVICES NOT SHOWING UNDER ASUS AURA LIKE MOTHERBOARD** 
- Uninstall all the AURA software. 
- Boot into your BIOS and disable the AURA/ROG Effects so all the RGB Lights and RGB Pins on the board turn off. 
- Shutdown the machine. 
- Boot back up into the BIOS and enable the AURA/ROG Effects so the lights start doing the default actions. 
- Install all the AURA Software again. 
- Devices should be showing now if not check the Advance Troubleshooting.  



###**ADVANCE TROUBLESHOOTING**

**AURA SOFTWARE WILL NOT RUN OR SAYS SERVICES ARE MISSING** 
This seems to stem from the AMD Chipset drivers causing the services to not correctly install or communicate with your motherboard/devices. There is only a few fixes you can try. Make sure you have tried everything above first.

**BEFORE TRYING**
You need to make sure you backup and data and or create a system restore point incase of any issues are to occur. Also you will need to uninstall all of the ASUS AURA Software before doing these steps. If you don't then it will still not work, a fresh install of the software needs to happen or you will be stuck with a still broken software.

**UPDATE TO THE LATEST CHIPSET DRIVERS**
Make sure you have the latest AMD Chipset drivers installed, you need to update to the latest one's provided by your Motherboards support page and see if that works or grab the latest from AMD's website under Driver Downloads (AMD may have newer then what ASUS provides for your motherboard so try the one on your device page first before getting AMD's). If grabbing the latest version still has issues try the next step.

**INSTALL OLDER CHIPSET DRIVERS**
Your next step would be to uninstall the Chipset drivers and install a older one provided by your motherboards support page or from AMD's website, there is a small text link button provided on their driver page to get older drivers. Just keep going back a update until you get one that works. Now this may not even work as sometimes you may run into an issue where Windows won't allow for the drivers to rollback due to service blocks or just not being able to remove the drivers.

**UNABLE TO INSTALL OLDER CHIPSET DRIVERS**
Your last option is to reformat Windows and start fresh. Again please backup all data before you do. Once you have reached the Windows Desktop follow the steps below.

- _DO NOT INSTALL ANYTHING FOR DRIVERS, UPDATES, NOTHING!_
- Install AURA Software and restart when asked
- Startup the software and make sure you have all devices showing
- Install AURA CONNECT and Razer Synapse 3, restart once you have signed into Razer Synapse and it's updated and install everything needed.
- Test AURA CONNECT is working.
- Update and install drivers as needed like normal.



###**NONE OF THESE STEPS WORKED!**
- Report the buggy software problems to ASUS. ASUS AURA is a mess of a program that needs to be taken to it's grave.
https://rog.asus.com/forum/forumdisplay.php?205-ASUS-Software



I think having these may help users that are having trouble with this so 1 they know 99% of the problem is not your software but with ASUS and 2 it gives them some steps to try and fix anything on their own. Anything I missed, or have misinformed too you can correct me, but I hope this does help.

**Comment by KyleStilkey** [comment]
Sure enough, the latest updated of ASUS ARMOURY has added support to my motherboard. I'm now able to move over and reduce my issues!

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
