### ISSUE TITLE
AuraConnect process high CPU usage

### ISSUE THREAD

**Issue by lord-slavik** [AndrewBabbitt97/AuraConnect#44]
AuraConnect.exe process has a high CPU usage over some time (~80%). Tried reinstalling it a couple of times the behavior continues to be displayed.

**Comment by AAlchemy** [comment]
Maybe antivirus software conflict? I had to exclude the apps folder.

**Comment by lord-slavik** [comment]
I have dissabled the antivirus and the behavior continues. I seems that it is progressive overtime. The CPU usage is low after booting up but it increases over time - after 2 hours from the boot up CPU usage of AuraConnects is around 40% 

![3](https://user-images.githubusercontent.com/64744422/80922780-efb5ec80-8d87-11ea-9cbf-c3916db15afa.PNG)
![1](https://user-images.githubusercontent.com/64744422/80922781-f04e8300-8d87-11ea-9a7f-59796c1ef97b.png)
![2](https://user-images.githubusercontent.com/64744422/80922782-f0e71980-8d87-11ea-96a4-cd52613bc1de.png)

**Comment by AndrewBabbitt97** [comment]
Enable perf metrics and upload your log: https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

**Comment by lord-slavik** [comment]
Uploaded the log for 1 hour running time

[AuraConnect - Copy.txt](https://github.com/AndrewBabbitt97/AuraConnect/files/4571563/AuraConnect.-.Copy.txt)

**Comment by AndrewBabbitt97** [comment]
Just looked at this.

So the thing to be aware of is that this is software controlled RGB, some devices have the ability (most keyboards, mice, etc) to do hardware based where the lighting is baked into the device firmware and such doesn't use CPU cycles to update. When we move to software, CPU usage will pretty much always be up if you are using a non static lighting mode (rainbow/wave, in game lighting, etc).

Everything looks fine, response times are low (around 1ms), and everything is working as intended in software. What I did note is that this is apparently a laptop? With that being said, it's already going to get hit harder in general on the CPU just because of that.

As for why the usage goes up, the pattern for update sends from Synapse don't change which really just leaves it up to something inside AURA using up extra CPU over time. I unfortunately don't have the source code for AURA, and as such there is nothing I can do to fix this issue for you. There is the potential that something is up with your AURA install in which case I'd recommend reinstalling, but with that said this bug is not in my code base and there is nothing I can do to fix it. I may be able to add a throttling feature, but this will only delay this bug inside AURA even longer it won't actually fix it and will just make the RGB effects worse.
