### ISSUE TITLE
Side Under Glow not Syncing with other RGB areas on my Motherboard {Asus X370 C6E}

### ISSUE THREAD

**Issue by Invicia** [AndrewBabbitt97/AuraConnect#58]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4750164/AuraConnect.log)

Everything {on my motherboard, peripherals and house lighting} is in sync properly, however one area in particular is not (Crosshair VI Extreme has a unique side under lighting that differentiates the model with Crosshair VI Hero, please see the pictures in google if that helps).
 I am currently on Armoury Crate for some reason if I use Aura it won't work properly hence I use armoury instead. But even after restarting and reinstalling there is no avail to it. Please help me solving this problem. 
Thank you for everything.

**Comment by AndrewBabbitt97** [comment]
Need your log files from C:\ProgramData\AuraConnect\logs

**Comment by AndrewBabbitt97** [comment]
Just saw the log in your post.

All board lights are typically under mainboard_master, I have yet to see any other ASUS board be done otherwise.

This is an issue with Aura, not my software. There's nothing I can do to fix this for you.

Reach out to ASUS on their forums, they are the only people that can get that fixed.
