### ISSUE TITLE
Not an issue but a suggestion

### ISSUE THREAD

**Issue by Iphantommenace** [AndrewBabbitt97/AuraConnect#79]
This could work for SteelSeries too, it would be very nice to have.

**Comment by AndrewBabbitt97** [comment]
Would go in another project I run called Chroma Connect, however typically the goal of it is to do in PC components, not exterior things. The biggest thing tends to be motherboards, keyboards present a huge issue in trying to support using this due to limitations of the Chroma API.

On another note, I do not have any logitec hardware to test this stuff with. This is where the community needs to step in a contribute. I don't have hardware from many manufacturers and so I can not test/develop for that hardware.
