### ISSUE TITLE
50% cpu usage

### ISSUE THREAD

**Issue by Crazybadx** [AndrewBabbitt97/AuraConnect#84]
I got a ryzen 5 2600 and auraconnect would sometimes use 30%-50% of my cpu other times it would be completely fine seems to be random also asus aura works fine by itself without high cpu usage so it's most likely auraconnect

**Comment by AndrewBabbitt97** [comment]
What lighting mode are you using?

**Comment by Crazybadx** [comment]
> What lighting mode are you using?

I'm just using spectrum cycling, I reinstalled it and it seems to be working fine but ill update you if it spikes up again

**Comment by AndrewBabbitt97** [comment]
If you see it spike again, try switching to static and see if it does it again.

It's always hard to say, but I don't recall any Intel based systems having CPU issues (aside from running things like rainbow puke which will always increase CPU usage) keep in mind the CPU SKU will change how much of an impact this seems to have. A lower end SKU will have a higher utilization than a high end one. For example I see a 4% usage from AuraConnect when using wave on a 10900k but it will probably go up on any other CPU due to it being heavily frequency bound. The higher the frequency the lower the usage will be from what I have seen.

**Comment by Crazybadx** [comment]
It went up to 40% again on static blue. It happened while I was playing rust could it be something to do with the game?

**Comment by AndrewBabbitt97** [comment]
Could be .NET optimization processes, but not sure. I have never been able to replicate this issue. And because I have never been able to replicate it, there's nothing I can do to fix it. Oddly enough every time I get complaints about CPU issues, iirc it's always AMD systems. So it could be something specific to the architecture.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
